
name: Build entity to twitter map

on: workflow_dispatch

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/spacy
        key: 'spacy.en_core_web_sm'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build
        python -m spacy download en_core_web_sm

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        pytest

    - name: Run
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/news_lk/entity_to_twitter.py

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp /tmp/news_lk.* .
        cp /tmp/README.md .
        echo "* $(date)" >> update.log
        git add .
        git commit -m "Updated data $(date)"
        git push origin data
